"use client";

import Image from "next/image";
import { forwardRef, useMemo } from "react";

import Field from "@/components/shared/field/Field";
import { Button } from "@/components/ui/button";
import { IMAGES } from "@/constants/files";
import { useAppSelector } from "@/hooks/storehooks";

interface PersonalInfoProps {
	onConfirm: () => void;
	type: string;
	ref: React.RefObject<HTMLDivElement>;
}

// eslint-disable-next-line react/display-name
const Preview = forwardRef<HTMLDivElement, PersonalInfoProps>(
	({ onConfirm, type }, ref) => {
		const data = useAppSelector(
			(state) => state.organization.organizationSlice
		);

		const displayedData = useMemo(() => {
			if (!data) return null;

			return data;
		}, [data]);

		const handlemodal = () => {
			// onIsOpenChange(true);
			onConfirm();
		};

		return (
			<>
				<div className="min-h-screen bg-gray-100 p-8 flex justify-center">
					{/* A4 size container */}
					<div
						className="bg-white w-[210mm] h-[297mm] shadow-lg p-12 relative"
						ref={ref}
					>
						<div className="border-b pb-6 mb-6">
							<h1 className="text-3xl font-bold text-gray-900">
								Organization Information Preview
							</h1>
							<h2 className="text-md font-semibold text-gray-700 mt-2">
								{`${data.name || ""} `}
							</h2>

							{/* {data.is_representative && ( */}
							<h3 className="text-md text-gray-600 mt-1">
								Contact Person :{" "}
								{`${data.contact_person_first_name || ""} ${data.contact_person_middle_name || ""} ${data.contact_person_last_name || ""}`}
							</h3>
							{/* )} */}

							<div className="text-sm text-gray-500 mt-2">
								Document generated on {new Date().toLocaleDateString()}
							</div>
						</div>

						<Image
							src={IMAGES.blueLogo}
							width={60}
							alt={"logo"}
							className="absolute top-12 right-12"
						/>

						{/* Content Grid */}
						{displayedData ? (
							<div className="grid grid-cols-2 gap-x-6 gap-y-6 text-sm">
								<div>
									<h2 className="text-lg font-semibold text-gray-900 mb-4">
										Basic Information
									</h2>
									<div className="space-y-3">
										{[
											"name",
											"registration_number",
											"industry_type",
											"number_of_employees",
											"company_website",
											"sector",
											"preferred_start_date",
										].map((key) => (
											<Field
												key={key}
												label={key}
												value={String(
													displayedData[key as keyof typeof displayedData] || ""
												)}
												local="OrganizationInfoForm.fields"
											/>
										))}
									</div>
								</div>

								<div>
									<h2 className="text-lg font-semibold text-gray-900 mb-4">
										Contact Information
									</h2>
									<div className="space-y-3">
										{[
											"phone_number",
											"email_address",
											"contact_person_first_name",
											"contact_person_middle_name",
											"contact_person_last_name",
											"contact_person_position",
											"contact_person_phone_number",
											"contact_person_email_address",
										].map((key) => (
											<Field
												key={key}
												label={key}
												value={String(
													displayedData[key as keyof typeof displayedData] || ""
												)}
												local="OrganizationInfoForm.fields"
											/>
										))}
									</div>
								</div>
								{/* Representative Information Section */}

								<div>
									<h2 className="text-lg font-semibold text-gray-900 mb-4">
										Organization Address Information
									</h2>
									<div className="space-y-3">
										{[
											"country",
											"street_address",
											"street_address_line2",
											"city",
											"region",
											"kifle_ketema",
											...(type === "ngo" ? ["country_of_origin"] : []), // Conditionally include "country"
										].map((key) => (
											<Field
												key={key}
												label={key}
												value={String(
													displayedData[key as keyof typeof displayedData] || ""
												)}
												local="OrganizationInfoForm.fields"
											/>
										))}
									</div>
								</div>
							</div>
						) : (
							<p>No data available to preview.</p>
						)}

						{/* Footer */}
						<div className="absolute bottom-8 left-12 right-12 text-xs text-gray-400 border-t pt-4">
							<div className="flex justify-between">
								<span>Generated by Tilla Health Insurance Provider System</span>
								<span>Page 1 of 1</span>
							</div>
						</div>
					</div>
					{/* Submit Button */}
					<div className="absolute bottom-20 right-12">
						<Button
							onClick={handlemodal}
							className="bg-green-500 hover:bg-green-600 text-white"
						>
							Confirm
						</Button>
					</div>
				</div>
			</>
		);
	}
);

export default Preview;
